spring:
  application:
    name: Service-Marketplace-Platform
  datasource:
    url: jdbc:mysql://localhost:3306/service_marketplace_platform
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect 
  transaction:
    default-timeout: 30
  servlet:
    multipart:
      max-request-size:
        5MB
      max-file-size:
        5MB
      enabled:
        true
      
     
app:
  upload:
    dir: uploads/
logging:
  level:
   com:
     marketplace:
       service: INFO
       controller: INFO